apiVersion: v1
kind: PersistentVolume
metadata:
  name: centos-pv-volume
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/dlambrig/uml/week12/umlF21"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: centos-pv-claim
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
