apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: centos-pv-claim
  containers:
    - name: task-pv-container
      image: centos
      command: ["/bin/bash","-c","while true; do sleep 1000; done"]
      volumeMounts:
        - mountPath: "/opt"
          name: task-pv-storage

